version: "3.4"
services:
  elastic-migrate:
    build:
      context: .
      target: base
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - ./:/home/elastic-migrate/:cached
      - /home/elastic-migrate/node_modules
      - ./migrations:/home/elastic-migrate/migrations
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
